version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static-data:/app/staticfiles
      - media-data:/app/media
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
