# Generated by Django 5.2.1 on 2025-05-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxsulot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
